openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080/
  description: Generated server url
paths:
  /api/billonaireClub/billionaire/{id}:
    get:
      tags:
      - billionaire-controller
      operationId: fetchBillionaire
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Billionaires'
    put:
      tags:
      - billionaire-controller
      operationId: update
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Billionaires'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
    delete:
      tags:
      - billionaire-controller
      operationId: delete
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
  /api/billonaireClub/billionaire:
    post:
      tags:
      - billionaire-controller
      operationId: save
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Billionaires'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
  /api/billonaireClub/billionaires:
    get:
      tags:
      - billionaire-controller
      operationId: findAll
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Billionaires'
components:
  schemas:
    Billionaires:
      type: object
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
        lastName:
          type: string
        company:
          type: string
        wealth:
          type: string
